kind = "web"
previewPath = "/"
title = "GLOWNDRY"
version = "1.0.0"
id = "artifacts/glowndry"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22208

[services.development]
run = "pnpm --filter @workspace/glowndry run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/glowndry", "run", "build" ]
publicDir = "artifacts/glowndry/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22208"
BASE_PATH = "/"
